apiVersion: postgresflex.stackit.cloud/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: postgresflex/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: mydb
    ownerSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
